import type { ListeningChallenge, PracticeCard, UsefulPhrase } from "./types";

export const practiceCardBank: PracticeCard[] = [
  { word: "Curious", translation: "Curioso/a", example: "I'm curious about how things work.", emoji: "🔎" },
  { word: "Brave", translation: "Valiente", example: "She was brave enough to try again.", emoji: "🦁" },
  { word: "Improve", translation: "Mejorar", example: "A little practice every day will help you improve.", emoji: "📈" },
  { word: "Journey", translation: "Viaje / recorrido", example: "Learning English is an exciting journey.", emoji: "🗺️" },
  { word: "Challenge", translation: "Reto", example: "This challenge looks difficult, but I can do it.", emoji: "🎯" },
  { word: "Discover", translation: "Descubrir", example: "We discover new words in every lesson.", emoji: "✨" },
  { word: "Confident", translation: "Seguro/a", example: "I feel more confident when I speak English.", emoji: "🚀" },
  { word: "Practice", translation: "Practicar", example: "Let's practice this sentence together.", emoji: "🎧" },
  { word: "Achievement", translation: "Logro", example: "Completing A1 is a great achievement.", emoji: "🏆" },
  { word: "Keep going", translation: "Sigue adelante", example: "Keep going — you're making great progress!", emoji: "⚡" },
  { word: "Kind", translation: "Amable", example: "It is important to be kind to other people.", emoji: "💛" },
  { word: "Healthy", translation: "Saludable", example: "A healthy breakfast gives you energy.", emoji: "🍎" },
  { word: "Explore", translation: "Explorar", example: "We love to explore new places together.", emoji: "🧭" },
  { word: "Friendly", translation: "Amigable", example: "Our new teacher is friendly and helpful.", emoji: "👋" },
  { word: "Imagine", translation: "Imaginar", example: "Imagine what cities will look like in the future.", emoji: "💭" },
  { word: "Choose", translation: "Elegir", example: "You can choose the activity you like most.", emoji: "✅" },
  { word: "Remember", translation: "Recordar", example: "I always remember to bring my notebook.", emoji: "🧠" },
  { word: "Amazing", translation: "Increíble", example: "The view from the mountain was amazing.", emoji: "🏔️" },
  { word: "Helpful", translation: "Servicial / útil", example: "This guide is helpful for new students.", emoji: "🤝" },
  { word: "Create", translation: "Crear", example: "Let's create a story with these new words.", emoji: "🎨" },
  { word: "Careful", translation: "Cuidadoso/a", example: "Be careful when you cross the street.", emoji: "🚦" },
  { word: "Decide", translation: "Decidir", example: "We need to decide where to go this weekend.", emoji: "🛤️" },
  { word: "Believe", translation: "Creer", example: "Believe in yourself and keep practising.", emoji: "🌟" },
  { word: "Different", translation: "Diferente", example: "Every person learns in a different way.", emoji: "🌈" },
  { word: "Together", translation: "Juntos", example: "We can solve the problem together.", emoji: "🧩" },
  { word: "Possible", translation: "Posible", example: "With practice, anything is possible.", emoji: "🚀" },
  { word: "Knowledge", translation: "Conocimiento", example: "Reading is a great way to build knowledge.", emoji: "📚" },
  { word: "Support", translation: "Apoyar", example: "Good friends support each other.", emoji: "🙌" },
  { word: "Opportunity", translation: "Oportunidad", example: "This course is an opportunity to learn something new.", emoji: "🚪" },
  { word: "Progress", translation: "Progreso", example: "Your progress grows with every small step.", emoji: "🌱" },
];

export const usefulPhraseBank: UsefulPhrase[] = [
  { phrase: "How are you doing today?", translation: "¿Cómo estás hoy?", emoji: "👋" },
  { phrase: "Could you say that again, please?", translation: "¿Podrías repetir eso, por favor?", emoji: "🔁" },
  { phrase: "I don't understand this word yet.", translation: "Todavía no entiendo esta palabra.", emoji: "🤔" },
  { phrase: "What does this expression mean?", translation: "¿Qué significa esta expresión?", emoji: "💬" },
  { phrase: "Can you speak a little more slowly?", translation: "¿Puedes hablar un poco más despacio?", emoji: "🐢" },
  { phrase: "I'd like to practise my English.", translation: "Me gustaría practicar mi inglés.", emoji: "🎧" },
  { phrase: "A little practice every day will help you improve.", translation: "Un poco de práctica diaria te ayudará a mejorar.", emoji: "📈" },
  { phrase: "Learning English is an exciting journey.", translation: "Aprender inglés es un viaje emocionante.", emoji: "🗺️" },
  { phrase: "This challenge looks difficult, but I can do it.", translation: "Este reto parece difícil, pero puedo hacerlo.", emoji: "🎯" },
  { phrase: "I'm ready to learn something new.", translation: "Estoy listo para aprender algo nuevo.", emoji: "✨" },
  { phrase: "Let me think about it for a moment.", translation: "Déjame pensarlo un momento.", emoji: "💭" },
  { phrase: "That's a really interesting idea.", translation: "Esa es una idea muy interesante.", emoji: "💡" },
  { phrase: "What are you going to do this weekend?", translation: "¿Qué vas a hacer este fin de semana?", emoji: "📅" },
  { phrase: "I usually get up at seven o'clock.", translation: "Normalmente me levanto a las siete.", emoji: "⏰" },
  { phrase: "The weather is perfect for a walk.", translation: "El clima está perfecto para caminar.", emoji: "☀️" },
  { phrase: "Could you help me find the station?", translation: "¿Podrías ayudarme a encontrar la estación?", emoji: "🚉" },
  { phrase: "I'd like a glass of water, please.", translation: "Quisiera un vaso de agua, por favor.", emoji: "🥤" },
  { phrase: "In my opinion, this is the best option.", translation: "En mi opinión, esta es la mejor opción.", emoji: "⭐" },
  { phrase: "I've never tried that before.", translation: "Nunca he intentado eso antes.", emoji: "🆕" },
  { phrase: "It was great talking to you.", translation: "Fue genial hablar contigo.", emoji: "😊" },
  { phrase: "Don't worry, we can try again.", translation: "No te preocupes, podemos intentarlo otra vez.", emoji: "💪" },
  { phrase: "I agree with you up to a point.", translation: "Estoy de acuerdo contigo hasta cierto punto.", emoji: "⚖️" },
  { phrase: "There are several ways to solve this problem.", translation: "Hay varias formas de resolver este problema.", emoji: "🧩" },
  { phrase: "The more you practise, the easier it becomes.", translation: "Cuanto más practicas, más fácil se vuelve.", emoji: "🌱" },
];

export const listeningChallenges: ListeningChallenge[] = [
  { phrase: "I usually have breakfast before school.", options: ["I usually have breakfast before school.", "I always have dinner after school.", "I rarely walk to school."], translation: "Normalmente desayuno antes de la escuela." },
  { phrase: "Could you tell me where the library is?", options: ["Can you open the library?", "Could you tell me where the library is?", "Do you work at the library?"], translation: "¿Podrías decirme dónde está la biblioteca?" },
  { phrase: "We are going to visit our grandparents this weekend.", options: ["We visited our grandparents last weekend.", "Our grandparents are visiting today.", "We are going to visit our grandparents this weekend."], translation: "Vamos a visitar a nuestros abuelos este fin de semana." },
  { phrase: "Learning a language takes time and patience.", options: ["Learning a language takes time and patience.", "Speaking quickly is always important.", "Languages are easy to forget."], translation: "Aprender un idioma requiere tiempo y paciencia." },
  { phrase: "In my opinion, the book was better than the film.", options: ["The film and the book were the same.", "In my opinion, the book was better than the film.", "I haven't watched the film yet."], translation: "En mi opinión, el libro fue mejor que la película." },
  { phrase: "Although it was raining, we decided to continue.", options: ["We stopped because it started raining.", "It rained after we arrived.", "Although it was raining, we decided to continue."], translation: "Aunque estaba lloviendo, decidimos continuar." },
];
